### ISSUE TITLE
Figure out how to store images of items

### ISSUE THREAD

**Issue by duci9y** [JumboCode/TUTV#54]
@71c is working on adding images to the backend. For development, these images will be stored on a local `MEDIA_ROOT` but for production, we need to figure out a cheap/free way to store them somewhere since Heroku storage is ephemeral.

**Comment by controversial** [comment]
Services I've used before:
- [Cloudinary](https://cloudinary.com/) has a generous free plan and is good at storing images etc; also has useful integration with a lot of back-end frameworks, for example [Keystone](https://github.com/keystonejs/keystone) has a `CloudinaryImage` type and Django might have something similar available
- I did one project that used [Airtable](https://airtable.com/) as the CMS which has built-in support for file uploads
- I'm working on a project right now that uses [Prismic](https://prismic.io/) as a CMS which also has a reasonably good system for uploading/retrieving media, and also serves it from their CDN. Prismic or Airtable probably **don't** make a lot of sense for this project, though, since they are targeted more at managing a website's entire content and might not be suitable as a media storage bucket that's disconnected from the data storage, as is the case for us.

**Comment by duci9y** [comment]
Let's implement Cloudinary!

**Comment by controversial** [comment]
Closing as we reached a conclusion; we should open new issues for the implementation.
