### ISSUE TITLE
The Request Summary page should display a loading indicator while waiting for data

### ISSUE THREAD

**Issue by duci9y** [JumboCode/TUTV#55]
Because it takes too long on first load sometimes. Try using an existing implementation.

**Comment by controversial** [comment]
Closed by #56

**Comment by duci9y** [comment]
We still should have a loading indicator because a fresh load of the page ends up taking ~12 seconds on Heroku.

**Comment by controversial** [comment]
I think this is because of the way I'm hosting the mock API  – if nobody queries the mock API for a long time Zeit "freezes" the server and it takes a while to start back up the next time someone makes a query. I can take a little time soon to move it to a "now v2" deployment that wouldn't have that problem. In any case, I don't think our API will have 12-second response times, but I can build a loader if it turns out to be an issue once we're using the real API.

My only hesitation to implement it now is that if it turns out the API request takes like <0.5 seconds, the appearance of a loading state could be jarring
